### PR TITLE
Add options to autoplay or loop video kinds

### PR DESCRIPTION
**Pull request by Ruxton**
Adds settings defaulting to false, to autoplay and loop the video in post kind video

### CODE REVIEW

**Comment by Ruxton** [comment]
@dshanske anything standing in the way of this?

**Comment by dshanske** [comment]
Major changes in how I'm doing media.

**Comment by dshanske** [comment]
I will be seeing about merging it when the new changes are finished.

**Comment by dshanske** [comment]
@Ruxton I'm pushing version 3.3.0 which completely changes how media handling is done. Haven't forgotten about this, but wanted to push out the storage changes.

**Pull request closed without merging**
