### PR TITLE
View

### PR DESCRIPTION
**Pull request by dshanske**
Improves Kind Views by adding page caching, moving image audio and video searches to the mf2 post class, passing variables each time, and tweaking the built-in views.

### CODE REVIEW

**Comment by miklb** [comment]
These look great. Can’t wait to test everything. Thanks

**Comment by dshanske** [comment]
@miklb Glad you like it. I'm trying to fix the doubled image problems people are having by moving the search code to its own function so it is easer to tweak, as well as fixing some minor rendering issues. Also, starting to look a little at page loading because of the database calls MF2_Post makes and I'm adding it to the non-persistent cache  it for the duration of the page load to ensure it doesn't have to be done twice.

**Comment by dshanske** [comment]
@miklb Are you up for testing the new master?

**Comment by miklb** [comment]
I will try tomorrow but still juggling multiple things. But I have a good feeling about the changes

**Comment by miklb** [comment]
I pulled down master last night and did a reply to a tweet url in Quill. it didn't display as a reply (regression)and Bridgy didn't pick it up as a reply. I didn't investigate any further. Using default view templates. Let me know if an issue would be a better place to discuss.

**Comment by dshanske** [comment]
I will test using the same methodology

**Comment by dshanske** [comment]
@miklb I tested replies using Quill and a tweet and it displayed on my testing site. https://tiny.n9n.us/2018/09/18/4981/ What did it show on your end?

**Comment by miklb** [comment]
https://miklb.com/blog/2018/09/17/4436/ 

When I look at the properties it shows the Twitter URL and the kind is set to reply. I'll have more time in a couple of days to debug more.

**Pull request merged**
